package org.clnlang.persistance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.clnlang.ast.visitor.CompilerVisitor;
import org.clnlang.compile.declaration.FunctionDeclImpl;
import org.clnlang.compile.declaration.GlobalVarDeclImpl;
import org.clnlang.compile.declaration.ProgramImpl;
import org.clnlang.compile.declaration.StructDeclImpl;
import org.clnlang.compile.declaration.UnionDeclImpl;
import org.clnlang.exception.ClnException;
import org.clnlang.parser.clnLexer;
import org.clnlang.parser.clnParser;
import org.clnlang.runtime.execution.Registry;
import org.clnlang.runtime.types.FullyQualifiedName;

/**
 * A ClnLoader backed by a JDBC database (designed for H2).
 *
 * <p>Recognition: set {@code CLN_PATH} (or {@code -cp}) to a JDBC URL, e.g.
 * {@code jdbc:h2:./mydb}.
 *
 * <p>The driver class is loaded explicitly from (in order of precedence):
 * <ol>
 *   <li>The {@code -cdd} / {@code --cln-db-driver} runtime argument</li>
 *   <li>The {@code CLN_DB_DRIVER} environment variable</li>
 *   <li>The built-in default {@value #DEFAULT_DRIVER}</li>
 * </ol>
 *
 * <p>Schema: table {@code CLN_SOURCE} is created automatically if absent.
 *
 * <pre>
 * CLN_SOURCE
 * ├── id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 * ├── package    VARCHAR(512) NOT NULL
 * ├── source     CLOB         NOT NULL
 * ├── createdAt  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
 * ├── updatedAt  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
 * └── version    INT          NOT NULL DEFAULT 1
 * </pre>
 */
public class H2Loader implements ClnLoader {

    static final String DEFAULT_DRIVER = "org.h2.Driver";

    private static final String DDL_CLN_SOURCE =
        "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
        "  id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
        "  package   VARCHAR(512) NOT NULL," +
        "  source    CLOB         NOT NULL," +
        "  createdAt TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP," +
        "  updatedAt TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP," +
        "  version   INT          NOT NULL DEFAULT 1" +
        ")";

    private final String jdbcUrl;
    private final String driverClass;
    private final List<String> sourceArgs;
    private final boolean verbose;

    /**
     * @param jdbcUrl     JDBC URL for the H2 database
     * @param driverClass Fully-qualified JDBC driver class name; {@code null} or blank
     *                    falls back to {@value #DEFAULT_DRIVER}
     * @param sourceArgs  Package names (or .cln file names) to execute
     * @param verbose     Whether to emit diagnostic output
     */
    public H2Loader(String jdbcUrl, String driverClass, List<String> sourceArgs, boolean verbose) {
        this.jdbcUrl = jdbcUrl;
        this.driverClass = (driverClass != null && !driverClass.isBlank()) ? driverClass : DEFAULT_DRIVER;
        this.sourceArgs = sourceArgs;
        this.verbose = verbose;
    }

    // -------------------------------------------------------------------------
    // ClnLoader
    // -------------------------------------------------------------------------

    @Override
    public int loadSources(Registry registry) throws Exception {
        loadDriver();
        int count = 0;

        try (Connection conn = openConnection()) {
            ensureSchema(conn);
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery(
                         "SELECT package, source FROM CLN_SOURCE ORDER BY id")) {
                while (rs.next()) {
                    String pkg = rs.getString("package");
                    String src = rs.getString("source");
                    try {
                        ProgramImpl program = compileSource(pkg, src);
                        String declaredPkg = pkg;
                        if (program.getPackageDecl() != null &&
                                program.getPackageDecl().getPackageName() != null) {
                            declaredPkg = program.getPackageDecl().getPackageName();
                        }
                        registry.addProgram(pkg, program, declaredPkg);
                        registerProgramSymbols(program, declaredPkg, registry);
                        count++;
                        log("  Loaded from DB: package=" + pkg);
                    } catch (Exception e) {
                        log("Warning: Failed to compile source for package '" + pkg + "': " + e.getMessage());
                    }
                }
            }
        }

        log("Total sources loaded from DB: " + count);
        return count;
    }

    @Override
    public StartupMode getSupportedStartupMode() {
        List<ClnSourceFile> files = getSourceFiles();
        if (files.isEmpty()) {
            throw new RuntimeException("No source package specified for database loader");
        }
        ClnSourceFile first = files.get(0);
        return first.isSourceFile() ? StartupMode.FILES : StartupMode.PACKAGE;
    }

    /**
     * Returns package-based source file references built from {@code sourceArgs}.
     * Actual source content is loaded from the database in {@link #loadSources}.
     */
    @Override
    public List<ClnSourceFile> getSourceFiles() {
        List<ClnSourceFile> result = new ArrayList<>();
        for (String sourceArg : sourceArgs) {
            if (sourceArg.endsWith(".cln")) {
                // Strip the extension and treat as a package lookup
                result.add(ClnSourceFile.fromPackage(sourceArg.substring(0, sourceArg.length() - 4)));
            } else {
                result.add(ClnSourceFile.fromPackage(sourceArg));
            }
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private void loadDriver() {
        try {
            Class.forName(driverClass);
            log("Loaded JDBC driver: " + driverClass);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("JDBC driver not found on classpath: " + driverClass +
                    ". Set CLN_DB_DRIVER (or -cdd) to the correct driver class.", e);
        }
    }

    private Connection openConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl);
    }

    private void ensureSchema(Connection conn) throws SQLException {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(DDL_CLN_SOURCE);
        }
    }

    private ProgramImpl compileSource(String packageId, String source) throws Exception {
        CharStream input = CharStreams.fromString(source, packageId);
        clnLexer lexer = new clnLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        clnParser parser = new clnParser(tokens);
        clnParser.ProgramContext programContext = parser.program();

        if (parser.getNumberOfSyntaxErrors() > 0) {
            throw new ClnException("Parsing failed for package '" + packageId +
                    "' with " + parser.getNumberOfSyntaxErrors() + " errors.");
        }

        CompilerVisitor compiler = new CompilerVisitor();
        return compiler.compileProgram(programContext);
    }

    private void registerProgramSymbols(ProgramImpl program, String packageName, Registry registry) {
        for (var decl : program.getDeclarations()) {
            if (decl instanceof FunctionDeclImpl) {
                FunctionDeclImpl funcDecl = (FunctionDeclImpl) decl;
                funcDecl.setPackageName(packageName);
                registry.registerFunction(
                        new FullyQualifiedName(packageName, funcDecl.getName()), funcDecl);
            } else if (decl instanceof StructDeclImpl) {
                StructDeclImpl structDecl = (StructDeclImpl) decl;
                registry.registerStructType(
                        new FullyQualifiedName(packageName, structDecl.getName()),
                        structDecl.toStructDefinition(packageName));
            } else if (decl instanceof UnionDeclImpl) {
                UnionDeclImpl unionDecl = (UnionDeclImpl) decl;
                registry.registerUnionType(
                        new FullyQualifiedName(packageName, unionDecl.getName()),
                        unionDecl.toUnionDefinition(packageName));
            } else if (decl instanceof GlobalVarDeclImpl) {
                GlobalVarDeclImpl varDecl = (GlobalVarDeclImpl) decl;
                varDecl.setPackageName(packageName);
                FullyQualifiedName fqn = new FullyQualifiedName(packageName, varDecl.getName());
                if (varDecl.isMutable()) {
                    registry.registerGlobalVariable(fqn, varDecl);
                } else {
                    registry.registerGlobalConstant(fqn, varDecl);
                }
            }
        }
    }

    private void log(String message) {
        if (verbose) {
            System.out.println(message);
        }
    }
}
