package org.clnlang.persistance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.clnlang.ast.visitor.CompilerVisitor;
import org.clnlang.compile.declaration.FunctionDeclImpl;
import org.clnlang.compile.declaration.GlobalVarDeclImpl;
import org.clnlang.compile.declaration.ProgramImpl;
import org.clnlang.compile.declaration.StructDeclImpl;
import org.clnlang.compile.declaration.UnionDeclImpl;
import org.clnlang.exception.ClnException;
import org.clnlang.parser.clnLexer;
import org.clnlang.parser.clnParser;
import org.clnlang.runtime.execution.Registry;
import org.clnlang.runtime.types.FullyQualifiedName;

/**
 * A {@link ClnLoader} backed by any JDBC-compatible database.
 *
 * <p>Recognition: set {@code CLN_PATH} (or {@code -cp}) to a JDBC URL, e.g.
 * {@code jdbc:h2:./mydb} or {@code jdbc:postgresql://host/db}.
 *
 * <p>The driver class is loaded explicitly from (in order of precedence):
 * <ol>
 *   <li>The {@code -cdd} / {@code --cln-db-driver} runtime argument</li>
 *   <li>The {@code CLN_DB_DRIVER} environment variable</li>
 *   <li>The built-in default {@value #DEFAULT_DRIVER} (H2)</li>
 * </ol>
 *
 * <p>The vendor is inferred automatically from the JDBC URL prefix via
 * {@link DbVendors#fromJdbc(String)}.  A vendor-specific {@code CREATE TABLE}
 * statement is used to ensure the {@code CLN_SOURCE} table exists.  For
 * unknown vendors the H2 dialect is used as a best-effort fallback.
 *
 * <p>Schema: table {@code CLN_SOURCE} is created automatically if absent.
 *
 * <pre>
 * CLN_SOURCE
 * ├── id         auto-increment primary key (dialect varies by vendor)
 * ├── package    VARCHAR(512) NOT NULL
 * ├── source     large-text column (CLOB / TEXT / LONGTEXT / NVARCHAR(MAX))
 * ├── createdAt  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
 * ├── updatedAt  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
 * └── version    INT          NOT NULL DEFAULT 1
 * </pre>
 */
public class JdbcLoader implements ClnLoader {

    static final String DEFAULT_DRIVER = "org.h2.Driver";

    private static final Map<DbVendors, String> DDL_BY_VENDOR;

    static {
        DDL_BY_VENDOR = new EnumMap<>(DbVendors.class);

        DDL_BY_VENDOR.put(DbVendors.H2,
            "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
            "  id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "  package   VARCHAR(512)  NOT NULL," +
            "  source    CLOB          NOT NULL," +
            "  createdAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INT           NOT NULL DEFAULT 1" +
            ")");

        DDL_BY_VENDOR.put(DbVendors.POSTGRESQL,
            "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
            "  id        BIGSERIAL     PRIMARY KEY," +
            "  package   VARCHAR(512)  NOT NULL," +
            "  source    TEXT          NOT NULL," +
            "  createdAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INT           NOT NULL DEFAULT 1" +
            ")");

        DDL_BY_VENDOR.put(DbVendors.MYSQL,
            "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
            "  id        BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY," +
            "  package   VARCHAR(512)  NOT NULL," +
            "  source    LONGTEXT      NOT NULL," +
            "  createdAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INT           NOT NULL DEFAULT 1" +
            ")");

        // MariaDB uses the same syntax as MySQL
        DDL_BY_VENDOR.put(DbVendors.MARIADB, DDL_BY_VENDOR.get(DbVendors.MYSQL));

        // SQL Server: IF NOT EXISTS guard via INFORMATION_SCHEMA check
        DDL_BY_VENDOR.put(DbVendors.SQLSERVER,
            "IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLN_SOURCE') " +
            "CREATE TABLE CLN_SOURCE (" +
            "  id        BIGINT         IDENTITY(1,1) PRIMARY KEY," +
            "  package   VARCHAR(512)   NOT NULL," +
            "  source    NVARCHAR(MAX)  NOT NULL," +
            "  createdAt DATETIME2      NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt DATETIME2      NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INT            NOT NULL DEFAULT 1" +
            ")");

        // Oracle: no IF NOT EXISTS before 23c; ORA-00955 is caught in ensureSchema
        DDL_BY_VENDOR.put(DbVendors.ORACLE,
            "CREATE TABLE CLN_SOURCE (" +
            "  id        NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "  package   VARCHAR2(512)  NOT NULL," +
            "  source    CLOB           NOT NULL," +
            "  createdAt TIMESTAMP      NOT NULL DEFAULT SYSTIMESTAMP," +
            "  updatedAt TIMESTAMP      NOT NULL DEFAULT SYSTIMESTAMP," +
            "  version   NUMBER(10)     NOT NULL DEFAULT 1" +
            ")");

        DDL_BY_VENDOR.put(DbVendors.DB2,
            "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
            "  id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
            "  package   VARCHAR(512)  NOT NULL," +
            "  source    CLOB          NOT NULL," +
            "  createdAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INT           NOT NULL DEFAULT 1" +
            ")");

        // SQLite: INTEGER PRIMARY KEY is implicitly an alias for the rowid (auto-increment).
        // CURRENT_TIMESTAMP yields 'YYYY-MM-DD HH:MM:SS' which is the idiomatic datetime in SQLite.
        DDL_BY_VENDOR.put(DbVendors.SQLITE,
            "CREATE TABLE IF NOT EXISTS CLN_SOURCE (" +
            "  id        INTEGER       PRIMARY KEY," +
            "  package   TEXT          NOT NULL," +
            "  source    TEXT          NOT NULL," +
            "  createdAt TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  updatedAt TEXT          NOT NULL DEFAULT CURRENT_TIMESTAMP," +
            "  version   INTEGER       NOT NULL DEFAULT 1" +
            ")");
    }

    private final String jdbcUrl;
    private final String driverClass;
    private final List<String> sourceArgs;
    private final boolean verbose;

    /**
     * @param jdbcUrl     JDBC URL for the database (e.g. {@code jdbc:postgresql://host/db})
     * @param driverClass Fully-qualified JDBC driver class name; {@code null} or blank
     *                    falls back to {@value #DEFAULT_DRIVER}
     * @param sourceArgs  Package names (or .cln file names) to execute
     * @param verbose     Whether to emit diagnostic output
     */
    public JdbcLoader(String jdbcUrl, String driverClass, List<String> sourceArgs, boolean verbose) {
        this.jdbcUrl = jdbcUrl;
        this.driverClass = (driverClass != null && !driverClass.isBlank()) ? driverClass : DEFAULT_DRIVER;
        this.sourceArgs = sourceArgs;
        this.verbose = verbose;
    }

    // -------------------------------------------------------------------------
    // ClnLoader
    // -------------------------------------------------------------------------

    @Override
    public int loadSources(Registry registry) throws Exception {
        loadDriver();
        int count = 0;

        try (Connection conn = openConnection()) {
            ensureSchema(conn);
            try (Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery(
                         "SELECT package, source FROM CLN_SOURCE ORDER BY id")) {
                while (rs.next()) {
                    String pkg = rs.getString("package");
                    String src = rs.getString("source");
                    try {
                        ProgramImpl program = compileSource(pkg, src);
                        String declaredPkg = pkg;
                        if (program.getPackageDecl() != null &&
                                program.getPackageDecl().getPackageName() != null) {
                            declaredPkg = program.getPackageDecl().getPackageName();
                        }
                        registry.addProgram(pkg, program, declaredPkg);
                        registerProgramSymbols(program, declaredPkg, registry);
                        count++;
                        log("  Loaded from DB: package=" + pkg);
                    } catch (Exception e) {
                        log("Warning: Failed to compile source for package '" + pkg + "': " + e.getMessage());
                    }
                }
            }
        }

        log("Total sources loaded from DB: " + count);
        return count;
    }

    @Override
    public StartupMode getSupportedStartupMode() {
        List<ClnSourceFile> files = getSourceFiles();
        if (files.isEmpty()) {
            throw new RuntimeException("No source package specified for database loader");
        }
        ClnSourceFile first = files.get(0);
        return first.isSourceFile() ? StartupMode.FILES : StartupMode.PACKAGE;
    }

    /**
     * Returns package-based source file references built from {@code sourceArgs}.
     * Actual source content is loaded from the database in {@link #loadSources}.
     */
    @Override
    public List<ClnSourceFile> getSourceFiles() {
        List<ClnSourceFile> result = new ArrayList<>();
        for (String sourceArg : sourceArgs) {
            if (sourceArg.endsWith(".cln")) {
                // Strip the extension and treat as a package lookup
                result.add(ClnSourceFile.fromPackage(sourceArg.substring(0, sourceArg.length() - 4)));
            } else {
                result.add(ClnSourceFile.fromPackage(sourceArg));
            }
        }
        return result;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private void loadDriver() {
        try {
            Class.forName(driverClass);
            log("Loaded JDBC driver: " + driverClass);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("JDBC driver not found on classpath: " + driverClass +
                    ". Set CLN_DB_DRIVER (or -cdd) to the correct driver class.", e);
        }
    }

    private Connection openConnection() throws SQLException {
        return DriverManager.getConnection(jdbcUrl);
    }

    private void ensureSchema(Connection conn) throws SQLException {
        DbVendors vendor = DbVendors.fromJdbc(jdbcUrl).orElse(DbVendors.H2);
        String ddl = DDL_BY_VENDOR.getOrDefault(vendor, DDL_BY_VENDOR.get(DbVendors.H2));
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(ddl);
        } catch (SQLException e) {
            // Oracle (pre-23c) doesn't support IF NOT EXISTS and raises ORA-00955
            // ("name already used by an existing object") when the table already exists.
            // Tolerate that specific error and continue; re-throw everything else.
            if (e.getErrorCode() != 955) {
                throw e;
            }
        }
    }

    private ProgramImpl compileSource(String packageId, String source) throws Exception {
        CharStream input = CharStreams.fromString(source, packageId);
        clnLexer lexer = new clnLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        clnParser parser = new clnParser(tokens);
        clnParser.ProgramContext programContext = parser.program();

        if (parser.getNumberOfSyntaxErrors() > 0) {
            throw new ClnException("Parsing failed for package '" + packageId +
                    "' with " + parser.getNumberOfSyntaxErrors() + " errors.");
        }

        CompilerVisitor compiler = new CompilerVisitor();
        return compiler.compileProgram(programContext);
    }

    private void registerProgramSymbols(ProgramImpl program, String packageName, Registry registry) {
        for (var decl : program.getDeclarations()) {
            if (decl instanceof FunctionDeclImpl) {
                FunctionDeclImpl funcDecl = (FunctionDeclImpl) decl;
                funcDecl.setPackageName(packageName);
                registry.registerFunction(
                        new FullyQualifiedName(packageName, funcDecl.getName()), funcDecl);
            } else if (decl instanceof StructDeclImpl) {
                StructDeclImpl structDecl = (StructDeclImpl) decl;
                registry.registerStructType(
                        new FullyQualifiedName(packageName, structDecl.getName()),
                        structDecl.toStructDefinition(packageName));
            } else if (decl instanceof UnionDeclImpl) {
                UnionDeclImpl unionDecl = (UnionDeclImpl) decl;
                registry.registerUnionType(
                        new FullyQualifiedName(packageName, unionDecl.getName()),
                        unionDecl.toUnionDefinition(packageName));
            } else if (decl instanceof GlobalVarDeclImpl) {
                GlobalVarDeclImpl varDecl = (GlobalVarDeclImpl) decl;
                varDecl.setPackageName(packageName);
                FullyQualifiedName fqn = new FullyQualifiedName(packageName, varDecl.getName());
                if (varDecl.isMutable()) {
                    registry.registerGlobalVariable(fqn, varDecl);
                } else {
                    registry.registerGlobalConstant(fqn, varDecl);
                }
            }
        }
    }

    private void log(String message) {
        if (verbose) {
            System.out.println(message);
        }
    }
}
